name: AudiSence Web - CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install PNPM Package Manager
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Build
        run: pnpm run build
